improving handle errors

diff --git a/.github/workflows/iac-tf-plan.yml b/.github/workflows/iac-tf-plan.yml
--- a/.github/workflows/iac-tf-plan.yml
+++ b/.github/workflows/iac-tf-plan.yml
@@ -119,30 +119,26 @@ jobs:
       - name: Terraform Init
         working-directory: ${{ inputs.project_name_directory }}
         run: |
-          # Initialize Terraform and capture warnings to fail on missing backend block
+          # Initialize Terraform and save output for later analysis
           terraform init -input=false \
             -backend-config="storage_account_name=${{ inputs.backend_storage_account_name }}" \
             -backend-config="container_name=${{ inputs.backend_container_name }}" \
             -backend-config="resource_group_name=${{ inputs.backend_resource_group_name }}" \
             -backend-config="key=${{ inputs.backend_path }}" \
           > init.log 2>&1
-          
-          # Show the init output
+          # Print init output
           cat init.log
-          
-          echo "::debug::About to run grep."
-          # Fail if Azure backend block is missing in main.tf
-          if grep -q "Warning: Missing backend configuration" init.log; then
-            echo "::error::GREP FOUND THE WARNING. THIS STEP SHOULD FAIL NOW."
-            echo "::error::Backend block missing in main.tf. Please add:"
-            echo "::error::terraform { backend \"azurerm\" {} }"
-            exit 1
-          else
-            echo "::debug::GREP DID NOT FIND THE WARNING."
-          fi
-          echo "::debug::Script finished without explicit exit."
         env:
           ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
+      
+      - name: Check Backend Configuration
+        run: |
+          # Fail if Terraform init logged missing backend configuration warning
+          if grep -q "Warning: Missing backend configuration" init.log; then
+            echo "::error::Backend block missing in configuration. Please add:"
+            echo "::error::terraform { backend \"azurerm\" {} }"
+            exit 1
+          fi
 
       - name: Login in Azure
         run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ inputs.azure_tenant_id }}
